export type AuthMethodSection = 'passwords' | 'mfa' | 'passwordless' | 'advanced' | 'session'
export type AuthMethodTag = 'mandatory' | 'recommended' | 'optional'

export interface AuthMethod {
  id: string
  section: AuthMethodSection
  name: string
  tag: AuthMethodTag
  enabled: boolean
  locked?: boolean
  iconColor: string
  iconBg: string
  desc: string
  /** Raw SVG inner markup (path/circle/rect elements) — see AuthMethodCard.tsx for why this is a string, not JSX. */
  iconSvg: string
}

/** Source: the `authMethods` array in sap-auth-settings_v3.html's inline script. */
export const authMethods: AuthMethod[] = [
  // Passwords & Credentials
  {
    id: 'pw',
    section: 'passwords',
    name: 'Password-Based Authentication',
    tag: 'mandatory',
    enabled: true,
    locked: true,
    iconColor: '#1d5cbf',
    iconBg: 'var(--blue-50)',
    desc: 'Standard username + password login. Passwords must meet complexity requirements: 12+ chars, uppercase, lowercase, number, special character, no spaces. Passwords expire every 90 days.',
    iconSvg:
      '<rect x="5" y="11" width="14" height="10" rx="2"/><path d="M12 15v2"/><circle cx="12" cy="15" r="1" fill="currentColor" stroke="none"/><path d="M8 11V7a4 4 0 118 0v4"/>',
  },
  {
    id: 'pwpolicy',
    section: 'passwords',
    name: 'Password Complexity Policy',
    tag: 'mandatory',
    enabled: true,
    locked: true,
    iconColor: 'var(--gray-700)',
    iconBg: 'var(--gray-100)',
    desc: 'Enforces minimum 12 characters, mixed case, numbers, special characters, no dictionary words, no reuse of last 12 passwords, and automatic expiry every 90 days.',
    iconSvg:
      '<path d="M11.35 3.836c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 00.75-.75 2.25 2.25 0 00-.1-.664m-5.8 0A2.251 2.251 0 0113.5 2.25H15a2.25 2.25 0 012.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V19.5a2.25 2.25 0 002.25 2.25h6.75a2.25 2.25 0 002.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 00-1.124-.08"/><path d="M10.5 10.5l1.5 1.5 3-3m-4.5 5l1.5 1.5 3-3"/>',
  },
  {
    id: 'secq',
    section: 'passwords',
    name: 'Security Questions',
    tag: 'optional',
    enabled: false,
    iconColor: '#d97706',
    iconBg: 'var(--amber-50)',
    desc: 'Backup identity verification using 2 pre-set questions (e.g., "What city were you born in?"). Used as fallback for password reset when MFA device is unavailable.',
    iconSvg:
      '<circle cx="12" cy="12" r="9"/><path d="M9.879 8.519c.585-.513 1.354-.769 2.121-.769s1.536.256 2.121.769c.586.512.879 1.175.879 1.856 0 .68-.293 1.344-.879 1.856-.203.179-.43.326-.67.442-.745.361-1.45.999-1.45 1.827v.75"/><circle cx="12" cy="18" r=".75" fill="currentColor" stroke="none"/>',
  },

  // MFA & OTP
  {
    id: 'totp',
    section: 'mfa',
    name: 'Authenticator App (TOTP)',
    tag: 'recommended',
    enabled: true,
    iconColor: 'var(--green-600)',
    iconBg: 'var(--green-50)',
    desc: 'Time-based one-time passwords generated by apps like Google Authenticator, Microsoft Authenticator, or Authy. Codes rotate every 30 seconds. Most phishing-resistant OTP method.',
    iconSvg: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 3"/><path d="M17.65 4.35l1.7-1.7M20.5 7h1.25"/>',
  },
  {
    id: 'smsotp',
    section: 'mfa',
    name: 'SMS One-Time Code',
    tag: 'optional',
    enabled: true,
    iconColor: '#0891b2',
    iconBg: '#ecfeff',
    desc: '6-digit code sent via SMS to your registered phone number. Convenient but vulnerable to SIM-swapping attacks. Not recommended as sole MFA method.',
    iconSvg:
      '<path d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m3.75 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375M21 12c0 4.556-4.03 8.25-9 8.25a9.764 9.764 0 01-2.555-.337A5.972 5.972 0 015.41 20.97a5.969 5.969 0 01-.474-.065 4.48 4.48 0 00.978-2.025c.09-.457-.133-.901-.467-1.226C3.93 16.178 3 14.189 3 12c0-4.556 4.03-8.25 9-8.25s9 3.694 9 8.25z"/>',
  },
  {
    id: 'emailotp',
    section: 'mfa',
    name: 'Email One-Time Code',
    tag: 'optional',
    enabled: true,
    iconColor: '#1d5cbf',
    iconBg: 'var(--blue-50)',
    desc: '6-digit code sent to your registered email address. Codes expire in 5 minutes. Useful as backup when phone is unavailable.',
    iconSvg:
      '<path d="M21.75 6.75v10.5a2.25 2.25 0 01-2.25 2.25h-15a2.25 2.25 0 01-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25m19.5 0v.243a2.25 2.25 0 01-1.07 1.916l-7.5 4.615a2.25 2.25 0 01-2.36 0L3.32 8.91a2.25 2.25 0 01-1.07-1.916V6.75"/><rect x="8" y="13" width="8" height="4" rx="1" fill="none"/><path d="M10 15h4"/>',
  },
  {
    id: 'pushnotif',
    section: 'mfa',
    name: 'Push Notification MFA',
    tag: 'optional',
    enabled: false,
    iconColor: '#9333ea',
    iconBg: 'var(--purple-50)',
    desc: 'Approve or deny login attempts via push notification on your registered mobile device. One-tap approval with device biometric confirmation.',
    iconSvg:
      '<path d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0"/>',
  },
  {
    id: 'hwkey',
    section: 'mfa',
    name: 'Hardware Security Key (U2F)',
    tag: 'optional',
    enabled: false,
    iconColor: 'var(--gray-700)',
    iconBg: 'var(--gray-100)',
    desc: 'Physical USB/NFC security key (YubiKey, Titan Key). Insert and tap to verify. Phishing-proof — the key verifies the domain cryptographically.',
    iconSvg:
      '<rect x="3" y="8" width="12" height="8" rx="2"/><circle cx="8" cy="12" r="2"/><path d="M15 10h5a2 2 0 012 2v0a2 2 0 01-2 2h-5"/><path d="M18 10V8m3 2V8"/>',
  },
  {
    id: 'biometric',
    section: 'mfa',
    name: 'Biometric Authentication',
    tag: 'optional',
    enabled: false,
    iconColor: '#e11d48',
    iconBg: '#fff1f2',
    desc: 'Fingerprint, face recognition, or iris scan via device hardware. Uses on-device biometric processors — biometric data never leaves the device.',
    iconSvg:
      '<path d="M7.864 4.243A7.5 7.5 0 0119.5 10.5c0 2.92-.556 5.709-1.568 8.268M5.742 6.364A7.465 7.465 0 004.5 10.5a48.667 48.667 0 00-1.318 7.57M12.75 10.5a2.25 2.25 0 00-4.5 0v.75a48.814 48.814 0 01-.858 8.574M7.5 10.5a4.5 4.5 0 019 0v.75c0 1.865-.085 3.71-.252 5.532"/>',
  },

  // Passwordless & SSO
  {
    id: 'magiclink',
    section: 'passwordless',
    name: 'Magic Link (Passwordless Email)',
    tag: 'optional',
    enabled: true,
    iconColor: '#8b5cf6',
    iconBg: 'var(--purple-50)',
    desc: 'One-time sign-in link sent to your email. Click the link to authenticate — no password needed. Links expire in 15 minutes and are single-use.',
    iconSvg:
      '<path d="M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244"/><path d="M9.813 15.904L9 18.75l-.813-2.846"/>',
  },
  {
    id: 'passkey',
    section: 'passwordless',
    name: 'FIDO2 / WebAuthn Passkeys',
    tag: 'recommended',
    enabled: true,
    iconColor: 'var(--green-600)',
    iconBg: 'var(--green-50)',
    desc: 'Cryptographic key pair stored on your device. Completely phishing-proof — the strongest passwordless method available. Syncs across devices via iCloud/Google.',
    iconSvg:
      '<path d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751"/><circle cx="16" cy="6" r="2" fill="none" stroke-width="1.5"/><path d="M17.5 7.5l1 2.5" stroke-width="1.5"/>',
  },
  {
    id: 'sso',
    section: 'passwordless',
    name: 'Single Sign-On (SAML 2.0)',
    tag: 'optional',
    enabled: true,
    iconColor: '#1d5cbf',
    iconBg: 'var(--blue-50)',
    desc: "Federated login via your organization's identity provider (Okta, Azure AD, Ping Identity). One login grants access to all connected applications.",
    iconSvg:
      '<path d="M3.75 6A2.25 2.25 0 016 3.75h2.25A2.25 2.25 0 0110.5 6v2.25a2.25 2.25 0 01-2.25 2.25H6a2.25 2.25 0 01-2.25-2.25V6zm0 9.75A2.25 2.25 0 016 13.5h2.25a2.25 2.25 0 012.25 2.25V18a2.25 2.25 0 01-2.25 2.25H6A2.25 2.25 0 013.75 18v-2.25zm9.75-9.75a2.25 2.25 0 012.25-2.25H18A2.25 2.25 0 0120.25 6v2.25A2.25 2.25 0 0118 10.5h-2.25a2.25 2.25 0 01-2.25-2.25V6zm0 9.75a2.25 2.25 0 012.25-2.25H18a2.25 2.25 0 012.25 2.25V18A2.25 2.25 0 0118 20.25h-2.25A2.25 2.25 0 0113.5 18v-2.25z"/>',
  },
  {
    id: 'oauth',
    section: 'passwordless',
    name: 'OAuth 2.0 / OpenID Connect',
    tag: 'optional',
    enabled: true,
    iconColor: '#0d9488',
    iconBg: '#f0fdfa',
    desc: 'Sign in with Google, Microsoft, or Apple using OAuth 2.0 with PKCE. The identity provider handles authentication; SAP receives only a verified token.',
    iconSvg: '<path d="M7.5 21L3 16.5m0 0L7.5 12M3 16.5h13.5m0-13.5L21 7.5m0 0L16.5 12M21 7.5H7.5"/>',
  },
  {
    id: 'pivcac',
    section: 'passwordless',
    name: 'PIV / CAC Smart Card',
    tag: 'optional',
    enabled: false,
    iconColor: 'var(--gray-700)',
    iconBg: 'var(--gray-100)',
    desc: 'Physical smart card authentication using Personal Identity Verification (PIV) or Common Access Card (CAC). Requires a card reader. Common in government and defense.',
    iconSvg:
      '<rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="9" cy="11" r="2.5"/><path d="M6 17c0-1.66 1.34-2.5 3-2.5s3 .84 3 2.5"/><path d="M15 9h3m-3 3h3m-3 3h2"/>',
  },
  {
    id: 'certauth',
    section: 'passwordless',
    name: 'Certificate-Based (mTLS)',
    tag: 'optional',
    enabled: false,
    iconColor: '#78350f',
    iconBg: '#fffbeb',
    desc: 'Client-side X.509 certificate installed on the device. Mutual TLS handshake verifies both client and server identity. Used for machine-to-machine and high-security scenarios.',
    iconSvg: '<circle cx="12" cy="9" r="5"/><path d="M12 14v7m-3 0h6"/><path d="M9.5 19l2.5-2 2.5 2"/><path d="M9.5 7.5L12 9.5l2.5-2"/>',
  },

  // Advanced & Adaptive
  {
    id: 'riskbased',
    section: 'advanced',
    name: 'Risk-Based / Adaptive Authentication',
    tag: 'recommended',
    enabled: true,
    iconColor: '#ea580c',
    iconBg: 'var(--orange-50)',
    desc: 'Dynamically adjusts authentication requirements based on risk signals: login location, device fingerprint, time of day, network, and behavioral patterns. Low-risk = password only; high-risk = full MFA.',
    iconSvg: '<path d="M3 12h2l3-9 4 18 3-9h2"/><circle cx="20" cy="12" r="1.5" fill="currentColor" stroke="none"/>',
  },
  {
    id: 'devicetrust',
    section: 'advanced',
    name: 'Device Trust / Fingerprinting',
    tag: 'optional',
    enabled: true,
    iconColor: '#4f46e5',
    iconBg: '#eef2ff',
    desc: 'Registers trusted devices based on hardware fingerprint (OS, browser, screen resolution, timezone). Unrecognized devices trigger additional verification steps.',
    iconSvg:
      '<path d="M9 17.25v1.007a3 3 0 01-.879 2.122L7.5 21h9l-.621-.621A3 3 0 0115 18.257V17.25m6-12V15a2.25 2.25 0 01-2.25 2.25H5.25A2.25 2.25 0 013 15V5.25m18 0A2.25 2.25 0 0018.75 3H5.25A2.25 2.25 0 003 5.25"/><path d="M10 10l1.5 1.5L14.5 8.5"/>',
  },
  {
    id: 'lockout',
    section: 'advanced',
    name: 'Account Lockout Policy',
    tag: 'mandatory',
    enabled: true,
    locked: true,
    iconColor: 'var(--red-600)',
    iconBg: 'var(--red-50)',
    desc: 'Automatically locks account after 5 consecutive failed login attempts. Lockout duration: 15 minutes. Admin can configure threshold (3–10 attempts) and duration (5–60 min).',
    iconSvg: '<rect x="5" y="11" width="14" height="10" rx="2"/><path d="M8 11V7a4 4 0 118 0v4"/><path d="M10 16l4-4m-4 0l4 4"/>',
  },

  // Session & Access
  {
    id: 'sessiontimeout',
    section: 'session',
    name: 'Session Timeout Policy',
    tag: 'mandatory',
    enabled: true,
    locked: true,
    iconColor: '#1d5cbf',
    iconBg: 'var(--blue-50)',
    desc: 'Sessions expire after 30 minutes of inactivity (configurable: 5–480 min). Absolute session lifetime: 12 hours. Users receive a 5-minute warning before timeout.',
    iconSvg:
      '<path d="M12 3v2m0 14v2m-7-9H3m18 0h-2"/><circle cx="12" cy="12" r="5"/><path d="M12 10v2.5l1.5 1"/><path d="M6.35 6.35l1.42 1.42m8.46-1.42l-1.42 1.42"/>',
  },
  {
    id: 'ipallow',
    section: 'session',
    name: 'IP Allowlisting / Geofencing',
    tag: 'optional',
    enabled: false,
    iconColor: '#0d9488',
    iconBg: '#f0fdfa',
    desc: 'Restrict login to specific IP addresses, CIDR ranges, or geographic regions. Requests from outside the allowlist are blocked with a 403 response.',
    iconSvg:
      '<path d="M12 21a9.004 9.004 0 008.716-6.747M12 21a9.004 9.004 0 01-8.716-6.747M12 21c2.485 0 4.5-4.03 4.5-9S14.485 3 12 3m0 18c-2.485 0-4.5-4.03-4.5-9S9.515 3 12 3m0 0a8.997 8.997 0 017.843 4.582M12 3a8.997 8.997 0 00-7.843 4.582m15.686 0A11.953 11.953 0 0112 10.5c-2.998 0-5.74-1.1-7.843-2.918"/><circle cx="12" cy="12" r="3"/>',
  },
  {
    id: 'concurrency',
    section: 'session',
    name: 'Concurrent Session Limit',
    tag: 'optional',
    enabled: true,
    iconColor: '#9333ea',
    iconBg: 'var(--purple-50)',
    desc: 'Limits the number of simultaneous active sessions per user. Default: 3 sessions. New logins beyond the limit terminate the oldest session automatically.',
    iconSvg: '<rect x="2" y="4" width="14" height="10" rx="1.5"/><rect x="8" y="8" width="14" height="10" rx="1.5"/><path d="M10 11h8m-8 3h5"/>',
  },
  {
    id: 'rbac',
    section: 'session',
    name: 'Role-Based Access Control (RBAC)',
    tag: 'mandatory',
    enabled: true,
    locked: true,
    iconColor: 'var(--gray-700)',
    iconBg: 'var(--gray-100)',
    desc: 'Users are assigned roles (Admin, Manager, User, Viewer, Auditor) that determine which portals, features, and data they can access. Follows principle of least privilege.',
    iconSvg:
      '<path d="M15 19.128a9.38 9.38 0 002.625.372 9.337 9.337 0 004.121-.952 4.125 4.125 0 00-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 018.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0111.964-3.07M12 6.375a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zm8.25 2.25a2.625 2.625 0 11-5.25 0 2.625 2.625 0 015.25 0z"/>',
  },
  {
    id: 'auditlog',
    section: 'session',
    name: 'Audit Logging & Monitoring',
    tag: 'mandatory',
    enabled: true,
    locked: true,
    iconColor: '#1d5cbf',
    iconBg: 'var(--blue-50)',
    desc: 'Every authentication event is logged: logins, logouts, MFA challenges, failed attempts, password changes, and permission changes. Logs are immutable and retained for 7 years.',
    iconSvg:
      '<path d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 002.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 00-1.124-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 00.75-.75 2.25 2.25 0 00-.1-.664m-5.8 0A2.251 2.251 0 0113.5 2.25H15a2.25 2.25 0 012.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25"/><circle cx="6.5" cy="12" r=".75" fill="currentColor" stroke="none"/><circle cx="6.5" cy="15" r=".75" fill="currentColor" stroke="none"/><circle cx="6.5" cy="18" r=".75" fill="currentColor" stroke="none"/>',
  },
]
